// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI9bgq08MSx0BTeaun94Iyk5tloGx6dW0',
    appId: '1:1076723570929:web:aef8ff0fae61e849de7150',
    messagingSenderId: '1076723570929',
    projectId: 'workshopmanager-29024',
    authDomain: 'workshopmanager-29024.firebaseapp.com',
    storageBucket: 'workshopmanager-29024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsxE0-kUiPPp2X9eu9ZxPqn1VGE-GrMCY',
    appId: '1:1076723570929:android:20a73792506c70fcde7150',
    messagingSenderId: '1076723570929',
    projectId: 'workshopmanager-29024',
    storageBucket: 'workshopmanager-29024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkAp8aq_D-7UxrPNWsPwZKyQbVmtfA9FA',
    appId: '1:1076723570929:ios:6995bccf4d18a3a4de7150',
    messagingSenderId: '1076723570929',
    projectId: 'workshopmanager-29024',
    storageBucket: 'workshopmanager-29024.firebasestorage.app',
    iosBundleId: 'my.edu.tarumt.workshopproManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkAp8aq_D-7UxrPNWsPwZKyQbVmtfA9FA',
    appId: '1:1076723570929:ios:6995bccf4d18a3a4de7150',
    messagingSenderId: '1076723570929',
    projectId: 'workshopmanager-29024',
    storageBucket: 'workshopmanager-29024.firebasestorage.app',
    iosBundleId: 'my.edu.tarumt.workshopproManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI9bgq08MSx0BTeaun94Iyk5tloGx6dW0',
    appId: '1:1076723570929:web:7d33d74f4b8cdb7dde7150',
    messagingSenderId: '1076723570929',
    projectId: 'workshopmanager-29024',
    authDomain: 'workshopmanager-29024.firebaseapp.com',
    storageBucket: 'workshopmanager-29024.firebasestorage.app',
  );

}